### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [fujaba/fulibMockups#13]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by Clashsoft** [comment]
Unfortunately not, we have no plans to continue the fulibScenarios syntax or the way fulibMockups models pages.

**Comment by ghost** [comment]
Hi Clashsoft.

> Unfortunately not, we have no plans to continue the fulibScenarios syntax or the way fulibMockups models pages.

thanks for feedback here.
